fullnameOverride: devoops-accommodation-service
replicaCount: 1

image:
  registry: docker.io
  repository: threeamigoscoding/devoops-accommodation-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  httpPort: 8080
  grpc:
    enabled: true
    port: 9090

ingress:
  enabled: false

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi

health:
  path: /actuator/health
  periodSeconds: 10
  failureThreshold: 3
  startup:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 60

configData:
  JAVA_TOOL_OPTIONS: "-XX:+UseSerialGC -Xms128m -Xmx384m -XX:ActiveProcessorCount=1"
  SERVER_PORT: "8080"
  LOGSTASH_HOST: "devoops-logstash:5000"
  ZIPKIN_HOST: "devoops-jaeger"
  ZIPKIN_PORT: "9411"
  POSTGRES_HOST: "devoops-postgres"
  POSGTES_PORT: "5432"
  MINIO_ENDPOINT: "http://devoops-minio:9000"
  MINIO_BUCKET: "accommodation-photos"
  GRPC_PORT: "9090"
  RESERVATION_GRPC_HOST: "devoops-reservation-service"
  RESERVATION_GRPC_PORT: "9090"

secretData:
  DB_USERNAME: "accommodation-service"
  DB_PASSWORD: "accommodation-service-pass"
  MINIO_ACCESS_KEY: "devoops"
  MINIO_SECRET_KEY: "devoops123"
